---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-gpu-pod
spec:
  priorityClassName: low-priority
  containers:
  - name: dummy
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
  runtimeClassName: nvidia
---
apiVersion: v1
kind: Pod
metadata:
  name: high-priority-gpu-pod
spec:
  priorityClassName: high-priority
  containers:
  - name: dummy
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "300"]
    resources:
      limits:
        nvidia.com/gpu: 1
  runtimeClassName: nvidia